version: '2'

services:
  web-app:
    container_name: web-app
    build:
      context: .
    command: npm start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    # TODO: add environment variables 
